// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentHealth
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocumentHealth.ebd2f3af-c274-4af6-bc9d-3e929361845d";
        public const string Name = "Document Health";
        public const string Description = @"Shows an icon above the vertical scroll bar indicating if the document has any errors or warnings.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
