// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentHealth
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocumentHealth.ebd2f3af-c274-4af6-bc9d-3e929361845d";
        public const string Name = "Document Health";
        public const string Description = @"Shows inline diagnostic messages and gutter glyphs, with inline/above/below placement and a scroll bar health icon.";
        public const string Language = "en-US";
        public const string Version = "1.1.901";
        public const string Author = "Mads Kristensen";
        public const string Tags = "errors, warnings, health";
        public const bool IsPreview = false;
    }
}
